version: "3"
services:
  app:
    container_name: stargateway
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"